services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=recetas.manudies.com
      - LETSENCRYPT_HOST=recetas.manudies.com
      - LETSENCRYPT_EMAIL=manudies@gmail.com
    volumes:
      - ./:/usr/share/nginx/html:ro
      ##En caso de que tenga rutass variables o se quiera configurar nginx##
      #- ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy
    external: true
